import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { InfoProvider } from "@/utils/lnfoContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full min-h-screen">
      <InfoProvider>
        <body className={`${inter.className} bg-[#faedcd] h-full`}>
          {children}
        </body>
      </InfoProvider>
    </html>
  );
}
